name: Deploy an backend and frontend
on: [push]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd FreakFightStatsProject/FreakFightStats
          git pull https://github.com/rczerwiec/FreakFightStats.git
          docker rmi backend
          docker build -t backend .
          cd client
          docker rmi frontend
          docker build -t frontend .
          cd ../..
          docker compose up -d